BODY_TYPE_TRANSLATION = {
"marine_container_20_feet": "20’ контейнер",
"marine_container_40_feet": "40’ контейнер",
"car_transporter_trailer": "Автовоз",
"autotower": "Автовышка",
"drop_side": "Борт",
"isothermal_railway_carriage": "Вагон изотермический",
"covered_railway_carriage": "Вагон крытый",
"refrigerator_railway_carriage": "Вагон рефрижератор",
"cargo_trailer_with_doppelstock": "Допельшток",
"graincarrier": "Зерновоз",
"isothermal_carriage_thermos": "ИВТ",
"isothermal": "Изотерма",
"inloader": "Инлоудер",
"container_ship_trailer": "Контейнеровоз",
"crane": "Кран",
"covered_carriage": "Крытый вагон",
"manipulator": "Манипулятор",
"mega_truck": "Мега фура",
"mega_long": "Мега-лонг",
"low_frame_trawl": "Низкорамный трал",
"platform_without_sides": "Площадка без бортов",
"refrigerator": "Реф",
"refrigerator_doppelstock": "Рефрижератор допельшток",
"refrigerator_vessel": "Рефрижераторное судно",
"dump_truck": "Самосвал",
"dump_grain_truck": "Самосвал зерновоз",
"special_equipment": "Спец-техника",
"curtainsider": "Тент",
"trawl": "Трал",
"cargo_van": "Цельнометаллический фургон",
"cement_truck": "Цементовоз",
"tank": "Цистерна"
}